### ISSUE TITLE
[ISSUE] - misc.c upstream cookie errors

### ISSUE THREAD

**Issue by diogomcreis95** [ashifa454/nginx-sticky-module-ng#1]
Hello there Ashifa!

We we're using your src code when we stumbled upon an error: nginx was truncating the set cookie headers.
Upon further code inspection, we noticed that the ngx_http_sticky_misc.c file has a small typo on line 80.
> We exchaged "path" for sameSite and it fixed our issue.

**Comment by ashifa454** [comment]
#2
